using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class GearButtonClicker : MonoBehaviour
{
    //A script attached to the button of each gear icon generated by GearsManager

    Image MyImage;
    Vector2 ButtonSize;
    float Offset = 15;
    Gears MyGear;
    int GearID;

    //Takes its info from GearsManager
    public void TakeInfo(Gears myGear, Sprite GearSprite, int gearID)
    {
        GearID = gearID;
        MyGear = myGear;
        ButtonSize = GetComponent<RectTransform>().sizeDelta;

        //Sets to the native size then changes it if it is higher or lower than a threshold
        MyImage = transform.Find("GearImage").GetComponent<Image>();
        RectTransform MyImageRT = transform.Find("GearImage").GetComponent<RectTransform>();
        MyImage.sprite = GearSprite;
        MyImage.SetNativeSize();

        if (MyImageRT.sizeDelta.x > ButtonSize.x - Offset)
        {
            MyImageRT.sizeDelta *= ((ButtonSize.x - Offset) / MyImageRT.sizeDelta.x);
        }

        if (MyImageRT.sizeDelta.y > ButtonSize.y - Offset)
        {
            MyImageRT.sizeDelta *= ((ButtonSize.y - Offset) / MyImageRT.sizeDelta.y);
        }
    }

    public void OnButtonClick()
    {
        GearsManager.instance.ChooseThisGear(MyGear, GearID);
        InventoryIconsManager.instance.ChangeIcon(MyGear, MyImage.sprite);
    }

}
