name: Unity Activate

on:
    workflow_dispatch: {}

### Refer to https://game.ci/docs/github/getting-started
jobs:
    checklicense:
        name: Check for UNITY_LICENSE in GitHub Secrets
        runs-on: ubuntu-latest
        outputs:
            is_unity_license_set: ${{ steps.checklicense_job.outputs.is_unity_license_set }}
        steps:
            - name: Check whether unity activation requests should be done
              id: checklicense_job
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              run: |
                  echo "Skip activation job: ${{ env.UNITY_LICENSE != '' }}"
                  export is_unity_license_set="${{ env.UNITY_LICENSE != '' }}"
                  echo "is_unity_license_set=$is_unity_license_set" >> $GITHUB_OUTPUT

    activation:
        needs: checklicense
        if: needs.checklicense.outputs.is_unity_license_set == 'false'
        name: Request manual activation file 🔑
        runs-on: ubuntu-latest
        steps:
            # Request manual activation file
            - name: Request manual activation file
              id: getManualLicenseFile
              uses: game-ci/unity-request-activation-file@v2
            # Upload artifact (Unity_v20XX.X.XXXX.alf)
            - name: Expose as artifact
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ steps.getManualLicenseFile.outputs.filePath }}
                  path: ${{ steps.getManualLicenseFile.outputs.filePath }}
