name: Unity Build Etra

on:
    workflow_run:
        workflows: 
            - Unity Build Addressable Extra
        types:
            - completed
    push:
        branches:
            - "master"
    workflow_dispatch: {}

### Refer to https://game.ci/docs/github/getting-started
jobs:
    build:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on:
            group: Default
            labels: ubuntu
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - iOS
                    - WebGL
        steps:
            # - name: Free Disk Space (Ubuntu)
            #   uses: jlumbroso/free-disk-space@main
            #   with:
            #       dotnet: false
            - uses: actions/checkout@v3
              with:
                  lfs: true
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
            - uses: actions/upload-artifact@v3
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build
    buildAndroid:
        name: Build for Android
        runs-on:
            group: Default
            labels: ubuntu
        steps:
            - uses: actions/checkout@v3
              with:
                  lfs: true
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-Android
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  targetPlatform: Android
                  androidKeystoreName: user.keystore
                  androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
                  androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
                  androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
                  androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
            - uses: actions/upload-artifact@v3
              with:
                  name: Build-Android
                  path: build
    # buildForMac:
    #     name: Build for StandaloneOSX
    #     runs-on: macos-latest
    #     steps:
    #         - uses: actions/checkout@v3
    #           with:
    #               lfs: true
    #         - uses: actions/cache@v3
    #           with:
    #               path: Library
    #               key: Library-StandaloneOSX
    #         - uses: game-ci/unity-builder@v2
    #           env:
    #               UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
    #               UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
    #               UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
    #           with:
    #               targetPlatform: StandaloneOSX
    #         - uses: actions/upload-artifact@v3
    #           with:
    #               name: Build-StandaloneOSX
    #               path: build

    buildForWindows:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: windows-2019
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - StandaloneWindows
                    # - StandaloneWindows64
        steps:
            - uses: actions/checkout@v3
              with:
                  lfs: true
            - uses: actions/cache@v3
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
            - uses: actions/upload-artifact@v3
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build
